### ISSUE TITLE
Buffalo Chicken prebuilt sandwich does not display information

### ISSUE THREAD

**Issue by AshleyTouchstone** [BrandonSoboleski/websitebnt#2]
Buffalo Chicken prebuilt sandwich does not show any ingredients or nutritional value. TC -1 

Steps to reproduce:
1. Select prebuilt and 6 in.
2. Select Buffalo Chicken
3. Select No, view nutritional values
4. View blank results page

**Comment by AshleyTouchstone** [comment]
The same problem occurs when selecting Tofu or Turkey and Cheese

**Comment by BrandonSoboleski** [comment]
Resolved
